### ISSUE TITLE
Are you accepting PR?

### ISSUE THREAD

**Issue by datatalking** [Sarvar-Anvarov/dreamjob#1]
I enjoyed reading your code and think you created something cool here.

Is there a way we can expand the code to include human resources webpages other than russia or we can make this available to other languages?

**Comment by Sarvar-Anvarov** [comment]
Hi, Andrew @datatalking, I'm so sorry for the late reply, I didn't receive any notification or, more likely, missed your message in the mail. 

Thank you for your time spent exploring this project, I'm glad you liked it. Answering your question, I can't spend any more time on this project, so I won't be able to accept any PR. But you can use this code as a template, I will be glad if this project helps someone.
